// Auto-generated by lenet_export.py (TAP-ORDER ROM)
// w_base is in 32-bit WORD units, not byte units
// Layout: [OC][TAP_GROUP][LANE]
// word_addr = W_BASE_xxx + oc * num_tap_groups + tap_group
#ifndef WBASE_TAP_H
#define WBASE_TAP_H

#define W_BASE_C1        0u   // num_tap_groups=7
#define W_BASE_C3       42u   // num_tap_groups=38
#define W_BASE_C5      650u   // num_tap_groups=64
#define W_BASE_F6     8330u   // num_tap_groups=30
#define W_BASE_OUT   10850u   // num_tap_groups=21

#define W_TOTAL_WORDS_TAP 11060u

#endif
